name: t
description: Telegram Client API (MTProto) to connect to Telegram and control a user programmatically.
version: 0.0.24
homepage: https://pwa.ir
repository: https://github.com/telegramflutter/t
topics:
 - telegram
 - tdlib

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
